backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use frontend\models\Record;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * RecordController implements the CRUD actions for Record model.
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Record models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Record::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Record model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Record model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Record();

        if ($model->load(Yii::$app->request->post())) {
          $model->img = UploadedFile::getInstance($model, 'img');
          if ($model->save()) {
            $model->upload();
            return $this->redirect(['view', 'id' => $model->id]);
          }


        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Record model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Record model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Record model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Record the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Record::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Record;
use yii\data\ActiveDataProvider;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */


    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
      $provider = new ActiveDataProvider([
          'query' => Record::find(),
          'pagination' => [
              'pageSize' => 6,
          ],
      ]);

        // get the posts in the current page
        $posts = $provider->getModels();
        return $this->render('index', ['posts' => $posts, 'provider' => $provider ]);
    }

    public function actionRecord($id){
      return $this->render('view', [
        'model' => $this->findRecord($id),
      ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    protected function findRecord($id)
    {
        if (($model = Record::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
  <td valign="top" style="width:530px">
<div id="g_D0A0F6B960324D418A4885B8CD98F4EF" class="AspNet-WebPartZone-Vertical">

					<div class="AspNet-WebPart">


<meta http-equiv="Content-Language" content="en-us">
<style type="text/css">
.style1 {
	font-size: medium;
}
.style2 {
	font-size: small;
}
.style5 {
	font-size: large;
	color: #686868;
}
</style>


<table style="text-align: justify; width: 760px">
	<tbody><tr>
		<td>
		<p>
		<img src="http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_1.jpg" width="760" height="200"></p>
		<p>&nbsp;</p>
		<p class="style1">«СИНГЕНТА» — ОДНА З ПРОВІДНИХ СВІТОВИХ КОМПАНІЙ, ЯКА
		ОБ’ЄДНУЄ ПОНАД 28 000 ФАХІВЦІВ У 90 КРАЇНАХ ЗАДЛЯ ДОСЯГНЕННЯ ОДНІЄЇ
		МЕТИ: РОЗКРИТИ ПОТЕНЦІАЛ РОСЛИНИ.</p>
		<p class="style1">&nbsp;</p>
		<p class="style2">Від часу свого заснування «Сингента» досягла значних
		успіхів і на сьогоднішній день є одним із лідерів світового агробізнесу,
		який оцінюється у понад 60 мільярдів доларів. Поточнення: увесь світовий
		агробізнес оцінюється у 60 мільярдів доларів чи ця цифра стосується лише
		«Сингенти»? Якщо йдеться про весь світовий бізнес, то речення
		переробляти не треба. До портфоліо «Сингенти» входить понад 80 засобів
		захисту рослин, а також велика кількість гібридів і сортів насіння
		польових та овочевих культур. В українському відділенні компанії працює
		більше 300 фахівців, серед яких багато кандидатів сільськогосподарських
		наук. Метою компанії «Сингента» в Україні є пропозиція комплексних
		рішень для українських аграріїв та партнерство, якому віддають перевагу
		українські та міжнародні компанії. «Сингенту» вирізняє високоякісна
		продукція, інтегрований підхід до вирішення поставлених завдань та
		використання переваг сільського господарства України.</p>
		<p class="style2">&nbsp;</p>
		<p class="style5"><strong>Головні напрямки компанії</strong></p>
		<p class="style1">&nbsp;</p>
		<p class="style2">
		<img src="http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_5_.jpg" width="760" height="10"></p>
		<p class="style1">&nbsp;</p>
				<table style="width: 760px">
            <tbody>
                <tr>
                    <td><a href="http://www3.syngenta.com/country/ua/uk/seeds/fieldcrops/Pages/fieldcrop.aspx" target="_blank"><img alt="" onmouseover="this.src='http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_3_.jpg'" onmouseout="this.src='http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_3.jpg'" style="border-top: 0px solid; border-right: 0px solid; border-bottom: 0px solid; border-left: 0px solid" src="http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_3.jpg"></a></td>
					<td><a href="http://www3.syngenta.com/country/ua/UK/CROPPROTECTION/CROPPROTECTION/Pages/home.aspx" target="_blank"><img alt="" onmouseover="this.src='http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_4_.jpg'" onmouseout="this.src='http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_4.jpg'" style="border-top: 0px solid; border-right: 0px solid; border-bottom: 0px solid; border-left: 0px solid" src="http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_4.jpg"></a></td>

 				</tr>
            </tbody>
        </table>

		<p class="style1">&nbsp;</p>
		<p class="style1">&nbsp;</p>
		<p class="style1">&nbsp;</p>
		<p class="style5"><strong>Чи знаєте Ви, що…</strong></p>
		<p class="style1">&nbsp;</p>
		<p class="style1">
		<img src="http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_5_.jpg" width="760" height="10"></p>
		<p class="style1">&nbsp;</p>
		<p class="style1">Багато відомих продуктів, які ми вживаємо, виготовлено
		з рослин компанії «Сингента»?</p>
		<p class="style1">&nbsp;</p>
		<p class="style2">Вимоги до тестування нашої продукції суворіші ніж до
		тестування ліків. Щоб вивести продукт на ринок, ми витрачаємо в
		середньому 200 млн доларів та 10 років на 180 наукових дослідів.</p>
		<p class="style2">&nbsp;</p>
		<p class="style2">Використовуючи засоби захисту рослин від «Сингенти»,
		фермери щороку вирощують 4,4 млн тонн бавовни. Цього достатньо, щоб
		забезпечити кожного у світі 3-ма футболками та кожного другого мешканця
		планети парою джинсів.</p>
		<p class="style1">&nbsp;</p>
		<p class="style1">
		<img src="http://www3.syngenta.com/country/ua/uk/aboutcompany/PublishingImages/KSV_2015/ksv_2.jpg" width="760" height="476"></p>
		<p class="style1">&nbsp;</p>
		<p class="style1">&nbsp;</p>
		<p>&nbsp;</p>
		<p>&nbsp;</p>
		<p>&nbsp;</p>
		</td>
	</tr>
</tbody></table>

					</div>
					</div>

</td>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">

    <div class="AspNet-WebPart">
						<img style="BORDER-BOTTOM: 0px solid; BORDER-LEFT: 0px solid; BORDER-TOP: 0px solid; BORDER-RIGHT: 0px solid" border="0" src="http://www3.syngenta.com/country/ua/uk/contacts/PublishingImages/contactsheader.jpg"> <img style="BORDER-BOTTOM: 0px solid; BORDER-LEFT: 0px solid; BORDER-TOP: 0px solid; BORDER-RIGHT: 0px solid" border="0" src="http://www3.syngenta.com/country/ua/uk/contacts/PublishingImages/contactsline.gif"> <br>
            <table style="WIDTH: 700px" summary="" width="500">
            <tbody>
            <tr>
            <td><span class="ms-rteCustom-H2">Контакти головного офісу ТОВ "Сингента" в Україні</span></td></tr></tbody></table><br>
            <table>
            <tbody>
            <tr>
            <td>
            <table style="WIDTH: 700px" summary="" width="500">
            <tbody>
            <tr>
            <td><font size="3"><strong>Заходьте до нас:<br></strong></font>03680<br>м. Київ,<br>вул. Козацька, 120/4</td>
            <td><strong><font size="3">Телефонуйте нам:<br></font></strong>тел. (044) 494 1771<br>0 (800) 50 04 49<br>факс. (044) 494 1770</td>
            <td>
            </td></tr></tbody></table>
            <hr width="700">
            </td></tr></tbody></table>
					</div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

use yii\helpers\Url;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="body-content">
        <div class="heading-info">
          <h1 class="text-center">
            Приветствуем на сайте компании "Алви Трейд"
          </h1>
        </div>
        <div class="container">
          <div class="row">
              <h2>Топ публикаций :</h2>
              <?php
                // var_dump($posts);
                foreach ($posts as $post ) {
                  echo "<div class='col-md-4 no-padding record-wrap'>
                          <img class='image' src='../uploads/$post->img' />
                          <h4>$post->title</h4>
                          <p>".mb_substr($post->description,0,200,"UTF-8")."..."."</p>
                          <a class='btn btn-md btn-success pull-right' href='".Url::to(['/site/record', 'id' => $post->id])."'>Read more</a>
                        </div>";
                }
              ?>



          </div>
        </div>


    </div>
</div>

<?php
echo \yii\widgets\LinkPager::widget([
  'pagination'=>$provider->pagination,
]);
 ?>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/view.php
<?php
use yii\helpers\Url;
?>


  <div class="row" style="margin-top:50px">
      <div class="col-md-6">
        <img src="../uploads/<?= $model->img ?>" style="width:500px;height:500px;" alt="" />
      </div>
      <div class="col-md-6">
        <h2><?= $model->title ?></h2>
        <p>
          <?= $model->description ?>
        </p>
        <a class='btn btn-md btn-primary' href="<?= Url::to(['/site/index']) ?>">Go back</a>
      </div>


  </div>